2008-07-04 16:30:52,924 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:32:18,875 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:32:20,293 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:34:39,388 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:35:18,136 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:35:39,719 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:36:08,069 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:39:03,235 Trac[web_ui] INFO: Disabling component trac.db.mysql_backend.MySQLConnector
2008-07-04 16:39:03,235 Trac[web_ui] INFO: Disabling component trac.db.postgres_backend.PostgreSQLConnector
2008-07-04 16:39:03,263 Trac[main] ERROR: [Errno 13] Permission denied: '/home/jick/project/jicknan/public_html/trac/conf/trac.ini'
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 206, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/admin/web_ui.py", line 113, in process_request
    path_info)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/admin/web_ui.py", line 394, in render_admin_panel
    self._do_update(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/admin/web_ui.py", line 478, in _do_update
    self.config.save()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/config.py", line 189, in save
    fileobj = open(self.filename, 'w')
IOError: [Errno 13] Permission denied: '/home/jick/project/jicknan/public_html/trac/conf/trac.ini'
2008-07-04 16:39:37,654 Trac[web_ui] INFO: Disabling component trac.db.mysql_backend.MySQLConnector
2008-07-04 16:39:37,655 Trac[web_ui] INFO: Disabling component trac.db.postgres_backend.PostgreSQLConnector
2008-07-04 16:39:37,703 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:39:37,965 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:40:02,526 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:40:02,652 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:40:08,693 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:40:08,818 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:40:20,376 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:40:20,508 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:40:31,727 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:40:31,851 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:40:49,393 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:40:49,517 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:42:59,593 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:42:59,708 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:42:59,773 Trac[web_ui] INFO: Disabling component trac.timeline.web_ui.TimelineModule
2008-07-04 16:42:59,823 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:43:00,058 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:43:06,350 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:43:06,478 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:43:12,441 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:43:12,569 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:43:13,948 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:43:14,052 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:43:25,153 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:43:25,276 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:44:07,277 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:44:07,442 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:44:14,099 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:44:14,222 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:44:40,888 Trac[web_ui] INFO: Disabling component trac.ticket.roadmap.MilestoneModule
2008-07-04 16:44:40,892 Trac[web_ui] INFO: Disabling component trac.ticket.roadmap.RoadmapModule
2008-07-04 16:44:40,937 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:44:41,143 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:44:47,447 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:44:47,575 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 16:47:24,318 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 16:47:24,443 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:04:29,041 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:04:29,223 Trac[env] ERROR: The user jick requires read _and_ write permission to the database file /home/jick/project/jicknan/public_html/trac/db/trac.db and the directory it is located in.
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 77, in get_connection
    return self._cnx_pool.get_cnx(self.timeout or None)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/pool.py", line 167, in get_cnx
    return _backend.get_cnx(self._connector, self._kwargs, timeout)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/pool.py", line 100, in get_cnx
    cnx = connector.get_connection(**kwargs)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/sqlite_backend.py", line 127, in get_connection
    return SQLiteConnection(path, params)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/sqlite_backend.py", line 170, in __init__
    user=getuser(), path=path))
TracError: The user jick requires read _and_ write permission to the database file /home/jick/project/jicknan/public_html/trac/db/trac.db and the directory it is located in.
2008-07-04 17:04:29,302 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:04:29,319 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-04 17:05:08,040 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:05:08,140 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:05:09,616 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:05:09,748 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:05:10,161 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:05:10,356 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:17:36,259 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:17:36,383 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:18:00,570 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:20:24,407 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:22:50,576 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:22:50,699 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:22:50,761 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:23:58,491 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:23:58,618 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:23:58,856 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:23:59,091 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:24:20,861 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:24:20,975 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:24:32,933 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:24:33,054 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:25:25,691 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:25:25,817 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:25:25,878 Trac[model] INFO: Updating component "TracServer"
2008-07-04 17:26:46,495 Trac[web_ui] INFO: Enabling component trac.timeline.web_ui.TimelineModule
2008-07-04 17:26:46,544 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:26:46,729 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:26:52,127 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:26:52,251 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:26:57,089 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:26:57,190 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:27:22,036 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:27:22,160 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:27:31,984 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:27:32,107 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:27:32,134 Trac[main] WARNING: 404 Not Found (No handler matched request to /milestone/)
2008-07-04 17:28:18,952 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:28:19,196 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:28:34,456 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:28:34,579 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:34:52,887 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:34:52,986 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:34:54,103 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:34:54,112 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:34:54,279 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:34:54,293 Trac[env] WARNING: base_url option not set in configuration, generated links may be incorrect
2008-07-04 17:38:19,847 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:38:21,135 Trac[session] INFO: Refreshing session a104ee4053ee4f09adf7f1c1
2008-07-04 17:38:22,632 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:38:22,686 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:39:13,370 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:39:24,285 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:42:33,670 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:42:34,035 Trac[main] WARNING: 404 Not Found (No handler matched request to /phpMyAdmin/)
2008-07-04 17:49:21,068 Trac[model] INFO: Updating component "P.K.M."
2008-07-04 17:50:05,124 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:51:01,141 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:51:01,466 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:52:43,983 Trac[model] INFO: Updating milestone "NR65S"
2008-07-04 17:52:43,997 Trac[model] INFO: Updating milestone field of all tickets associated with milestone "NR65S"
2008-07-04 17:53:39,970 Trac[model] INFO: Updating milestone "P.K.M."
2008-07-04 17:53:39,974 Trac[model] INFO: Updating milestone field of all tickets associated with milestone "P.K.M."
2008-07-04 17:54:11,891 Trac[model] INFO: Updating milestone "TracServer"
2008-07-04 17:54:11,900 Trac[model] INFO: Updating milestone field of all tickets associated with milestone "TracServer"
2008-07-04 17:54:11,936 Trac[env] INFO: Reloading environment due to configuration change
2008-07-04 17:55:05,379 Trac[model] INFO: Updating milestone "SerComm"
2008-07-04 17:55:05,383 Trac[model] INFO: Updating milestone field of all tickets associated with milestone "SerComm"
2008-07-09 09:29:56,132 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:29:56,312 Trac[main] WARNING: 500 Trac Error (Unsupported database type "mysql")
2008-07-09 09:30:20,049 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:31:15,511 Trac[session] INFO: Refreshing session jick
2008-07-09 09:31:39,534 Trac[web_ui] INFO: Enabling component trac.db.mysql_backend.MySQLConnector
2008-07-09 09:31:39,594 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:32:52,016 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:32:52,117 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:32:52,130 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:36:27,957 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:36:29,127 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:36:30,554 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:36:30,611 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:36:59,527 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:37:26,195 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:23,604 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:23,697 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:23,708 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:34,882 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:34,930 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:34,989 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:35,064 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:35,072 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:35,081 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:35,861 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:35,899 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:35,937 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:35,980 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:36,034 Trac[env] INFO: Reloading environment due to configuration change
2008-07-09 09:41:36,058 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:36,109 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:36,115 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:36,125 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:36,138 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:36,143 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:36,184 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:36,197 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:41:36,201 Trac[env] ERROR: Unsupported database type "mysql"
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 574, in open_environment
    needs_upgrade = env.needs_upgrade()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 412, in needs_upgrade
    db = self.get_db_cnx()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/env.py", line 257, in get_db_cnx
    return DatabaseManager(self).get_connection()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 75, in get_connection
    connector, args = self._get_connector()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/db/api.py", line 99, in _get_connector
    scheme=scheme))
TracError: Unsupported database type "mysql"
2008-07-09 09:41:36,243 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:26,442 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:29,888 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:35,338 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:58,805 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:58,859 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:58,939 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:59,028 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:59,252 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:59,335 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:59,372 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:57:59,435 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:58:04,617 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:58:04,652 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:58:14,499 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 09:58:15,986 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:41,035 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:42,541 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:43,193 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:43,744 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:44,397 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:44,678 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:45,311 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:46,461 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:47,163 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:47,842 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:48,266 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:48,512 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:48,766 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:48,985 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:49,315 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:49,783 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:49,898 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:49,981 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:50,035 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:50,385 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:50,421 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:50,458 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:15:50,526 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:00,981 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:02,714 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:03,352 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:03,965 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:04,230 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:04,792 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:05,154 Trac[session] INFO: Refreshing session jick
2008-07-09 10:16:07,449 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:09,241 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:09,543 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:09,961 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:09,995 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:10,039 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:10,122 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:21,007 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:28,635 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:29,962 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:30,607 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:31,093 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:31,395 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:31,638 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:32,122 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:32,262 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:32,448 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:33,008 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:33,595 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:33,996 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:34,235 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:34,851 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:35,539 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,414 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,465 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,558 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,609 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,867 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,915 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:36,989 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:44,711 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:44,809 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:44,883 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:44,948 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:44,996 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:45,042 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:45,111 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:16:51,329 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:02,399 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:04,257 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:05,015 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:05,662 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:06,292 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:06,826 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:07,343 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:08,265 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:09,251 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:09,809 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:10,332 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:10,926 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:11,492 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:12,154 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:13,333 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:14,129 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:17:14,173 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:16,444 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:18,741 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:19,506 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:20,073 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:20,331 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:20,974 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:21,548 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:23,953 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:24,041 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:24,144 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:24,472 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:24,508 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:24,551 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:24,688 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:38,481 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:38,701 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:38,831 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
2008-07-09 10:18:38,860 Trac[main] ERROR: translations
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 447, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/web/main.py", line 257, in dispatch
    translation.deactivate()
  File "/usr/lib/python2.5/site-packages/Trac-0.12dev-py2.5.egg/trac/util/translation.py", line 114, in deactivate
    del _current.translations
AttributeError: translations
